"""LanceDB storage via LlamaIndex's LanceDBVectorStore. Implements our StorageInterface."""

import fcntl
import hashlib
import json
import logging
import os
import re
import shutil
import subprocess
import sys
import threading
from collections import Counter
from contextlib import contextmanager, nullcontext
from pathlib import Path
from typing import Any

import pyarrow as pa
from llama_index.core.schema import TextNode, NodeRelationship, RelatedNodeInfo
from llama_index.vector_stores.lancedb import LanceDBVectorStore
from llama_index.vector_stores.lancedb.base import TableNotFoundError

from core.storage import SearchHit
from core.tracing import get_tracer
from doc_enrichment import CORE_ENRICHMENT_FIELDS

logger = logging.getLogger(__name__)

# Lazy tracer (resolves provider per call); spans are no-ops when tracing is off.
_tracer = get_tracer("pipeline")

_SAFE_IDENTIFIER_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*$")
_CORRUPT_LANCE_MARKERS = (
    "lanceerror(io)",
    "invalid range 0..0",
    "manifest was not found",
)
_LANCE_CORRUPTION_MARKERS = _CORRUPT_LANCE_MARKERS
_STALE_READ_MARKERS = (
    ".lance/_versions/",
    ".lance/data/",
    ".lance/_deletions/",
    "manifest was not found",
)

_EXTRA_META_FIELDS = ("description", "author", "keywords", "custom_meta")
_ENRICHMENT_AUX_FIELDS = ("enr_importance_source",)
_DUPLICATE_META_FIELDS = (
    "dup_count",
    "dup_sources",
    "dup_locations",
    "dup_archive_paths",
    "dup_natural_keys",
)

# Metadata keys owned and regenerated by LlamaIndex's node_to_metadata_dict()
# on every write. They must never be carried from a read-back row into a new
# TextNode's metadata: the fresh `_node_content` serialization embeds
# node.metadata, so a stale `_node_content` carried forward gets nested inside
# itself and JSON escaping roughly doubles it on every duplicate merge —
# growing single rows to hundreds of MB and breaking Lance page decoding
# (Arrow i32 offset overflow) during table.optimize()/compaction (#0108).
_LLAMA_MANAGED_METADATA_KEYS = frozenset({
    "_node_content",
    "_node_type",
    "document_id",
    "doc_id",
    "ref_doc_id",
})


_DEFAULT_LANCE_VERSION_RETENTION_MINUTES = 30.0
_DEFAULT_DAILY_RESTORE_POINT_DAYS = 7
_DAILY_TAG_PREFIX = "daily-"
_DOCUMENT_WRITE_LOCK_STRIPES = 256
_COMPACTION_MARKER_SUFFIX = ".last-compaction"
_PROCESS_DOCUMENT_LOCKS: dict[str, threading.RLock] = {}
_PROCESS_DOCUMENT_LOCKS_GUARD = threading.Lock()


def _lance_version_retention_minutes() -> float:
    """Retention window for Lance version pruning (env-tunable).

    Versions younger than this are kept so in-flight readers are never cut off;
    older ones are reclaimed each indexing run. Non-positive/invalid disables
    the guard band (prune everything superseded, most aggressive)."""
    raw = os.environ.get("LANCE_VERSION_RETENTION_MINUTES")
    if raw is None:
        return _DEFAULT_LANCE_VERSION_RETENTION_MINUTES
    try:
        val = float(raw)
    except (TypeError, ValueError):
        return _DEFAULT_LANCE_VERSION_RETENTION_MINUTES
    return max(0.0, val)


def _daily_restore_point_days() -> int:
    """How many daily version tags to keep as logical restore points — exactly
    N points: today plus N-1 prior days (env-tunable via
    LANCE_DAILY_RESTORE_POINTS). 0 disables the feature and removes any
    previously created daily tags.

    Each daily tag pins that day's superseded data files against the version
    prune, so `git reset`-style rollback to a past day stays possible. That
    pinning is also why the window must stay small: with daily compaction,
    every retained tag holds one full rewrite of the table on disk (#0232)."""
    raw = os.environ.get("LANCE_DAILY_RESTORE_POINTS")
    if raw is None:
        return _DEFAULT_DAILY_RESTORE_POINT_DAYS
    try:
        return max(0, int(raw))
    except (TypeError, ValueError):
        return _DEFAULT_DAILY_RESTORE_POINT_DAYS


def _daily_tag_name(day) -> str:
    return f"{_DAILY_TAG_PREFIX}{day.isoformat()}"


def _parse_daily_tag_date(name: str):
    """Return the date encoded in a `daily-YYYY-MM-DD` tag, or None if the tag
    isn't one of ours (so we never touch tags created by anything else)."""
    from datetime import date

    if not name.startswith(_DAILY_TAG_PREFIX):
        return None
    try:
        return date.fromisoformat(name[len(_DAILY_TAG_PREFIX):])
    except ValueError:
        return None


def _is_retryable_commit_conflict(exc: BaseException) -> bool:
    """True for Lance's transient 'Retryable commit conflict' raised when a
    prune races a concurrent write — safe to retry."""
    text = str(exc).lower()
    return "retryable commit conflict" in text or (
        "conflict" in text and "retry" in text
    )


def _strip_llama_managed_keys(meta: dict) -> dict:
    """Drop LlamaIndex-managed keys from read-back metadata before it is put
    on a new TextNode. All of them are regenerated from the node at write
    time, and `doc_id` is re-derived from the SOURCE relationship."""
    return {k: v for k, v in meta.items() if k not in _LLAMA_MANAGED_METADATA_KEYS}

# All metadata keys that map to explicit SearchHit attributes.
# Anything NOT in this set goes into SearchHit.extra_metadata.
_CORE_META_KEYS = {
    "doc_id", "source_type", "mtime", "size", "title", "tags", "folder",
    "status", "created", "loc", "snippet", "rel_path",
    "description", "author", "keywords", "custom_meta",
    *CORE_ENRICHMENT_FIELDS,
    *_ENRICHMENT_AUX_FIELDS,
}


def _extract_enrichment(meta: dict) -> dict[str, str]:
    """Pull enrichment + extra metadata fields from metadata, defaulting to empty strings."""
    result = {f: meta.get(f, "") or "" for f in CORE_ENRICHMENT_FIELDS}
    for f in _ENRICHMENT_AUX_FIELDS:
        result[f] = meta.get(f, "") or ""
    for f in _EXTRA_META_FIELDS:
        result[f] = meta.get(f, "") or ""
    return result


def _extract_extra_metadata(meta: dict) -> dict[str, str]:
    """Collect metadata fields not in the hardcoded core set (e.g. section, sentiment)."""
    return {k: str(v) for k, v in meta.items() if k not in _CORE_META_KEYS and v}


def _json_string_list(value: Any) -> list[str]:
    """Decode a JSON list string, preserving plain strings as single-item lists."""
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item) for item in value if str(item).strip()]
    if isinstance(value, str):
        stripped = value.strip()
        if not stripped:
            return []
        try:
            parsed = json.loads(stripped)
        except json.JSONDecodeError:
            return [stripped]
        if isinstance(parsed, list):
            return [str(item) for item in parsed if str(item).strip()]
        return [str(parsed)] if str(parsed).strip() else []
    text = str(value).strip()
    return [text] if text else []


def _append_unique(items: list[str], value: Any) -> None:
    """Append a non-empty string if it is not already present."""
    text = str(value).strip()
    if text and text not in items:
        items.append(text)


def _duplicate_natural_key(duplicate_ref: dict[str, Any]) -> str:
    """Resolve a natural key from explicit metadata or a source-qualified doc_id."""
    natural_key = str(duplicate_ref.get("natural_key") or "").strip()
    if natural_key:
        return natural_key
    source_name = str(duplicate_ref.get("source_name") or "").strip().lower()
    if source_name in {"documents", "filesystem"}:
        return ""
    doc_id = str(duplicate_ref.get("doc_id") or "").strip()
    if "::" not in doc_id:
        return ""
    return doc_id.split("::", 1)[1].strip()


class LanceDBStore:
    """Implements StorageInterface using LlamaIndex's LanceDBVectorStore."""

    def __init__(self, index_root: str | Path, table_name: str = "chunks") -> None:
        self.index_root = str(Path(index_root))
        self.table_name = table_name
        self._schema_lock = threading.Lock()
        self._completed_insert_doc_ids: set[str] = set()
        self._exclusive_writer_depth = 0
        self._memory_observer = None
        self._vs = self._build_vector_store()
        self._ensure_scalar_index()
        try:
            self._probe_table_read()
        except Exception as exc:
            if not self._is_probable_corruption_error(exc) or not self._recover_corrupt_table():
                raise
            logger.warning(
                "Recovered probable LanceDB corruption while opening %s: %s",
                self.table_name,
                exc,
            )
            self._vs = self._build_vector_store()
            self._ensure_scalar_index()
            self._probe_table_read()

    def set_memory_observer(self, observer: Any | None) -> None:
        """Attach optional index memory instrumentation to storage writes."""
        self._memory_observer = observer

    @contextmanager
    def exclusive_writer_session(self):
        """Use one stable handle while an external table lock excludes peers."""
        self._exclusive_writer_depth += 1
        try:
            yield self
        finally:
            self._exclusive_writer_depth -= 1

    def _measure_memory(self, subphase: str, **fields: Any):
        observer = self._memory_observer
        measure = getattr(observer, "measure", None)
        if not callable(measure):
            return nullcontext()
        try:
            return measure(subphase, **fields)
        except Exception:
            logger.debug("Cannot create memory measurement for %s", subphase, exc_info=True)
            return nullcontext()

    @contextmanager
    def _serialize_document_writes(self, doc_ids: set[str] | list[str]):
        """Serialize same-document rewrites across threads and processes."""
        stripe_indexes = sorted(
            {
                int.from_bytes(
                    hashlib.blake2b(str(doc_id).encode(), digest_size=2).digest(),
                    "big",
                )
                % _DOCUMENT_WRITE_LOCK_STRIPES
                for doc_id in doc_ids
                if doc_id
            }
        )
        lock_root = Path(self.index_root) / ".lancedb-write-locks"
        lock_paths = [
            lock_root / f"{self.table_name}-{index:03d}.lock"
            for index in stripe_indexes
        ]
        with _PROCESS_DOCUMENT_LOCKS_GUARD:
            locks = [
                _PROCESS_DOCUMENT_LOCKS.setdefault(
                    str(path.resolve()), threading.RLock()
                )
                for path in lock_paths
            ]
        for lock in locks:
            lock.acquire()
        lock_files = []
        try:
            lock_root.mkdir(parents=True, exist_ok=True)
            for path in lock_paths:
                lock_file = path.open("a+")
                try:
                    fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
                except Exception:
                    lock_file.close()
                    raise
                lock_files.append(lock_file)
            yield
        finally:
            for lock_file in reversed(lock_files):
                try:
                    fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)
                finally:
                    lock_file.close()
            for lock in reversed(locks):
                lock.release()

    def _build_vector_store(self) -> LanceDBVectorStore:
        return LanceDBVectorStore(
            uri=self.index_root,
            table_name=self.table_name,
            mode="create",  # "create" lets LanceDB create the table if missing, or open if exists
        )

    @staticmethod
    def _is_probable_corruption_error(exc: Exception) -> bool:
        text = str(exc).lower()
        return _looks_like_corrupt_lance_error(exc) or "corrupt" in text

    def _probe_table_read(self) -> None:
        """Cheap read probe so init fails fast on unreadable tables, not first user query."""
        try:
            self._vs.table.to_lance().to_table(limit=1)
        except TableNotFoundError:
            return

    def _recover_corrupt_table(self) -> bool:
        """Rollback to the newest readable Lance version and rewrite the dataset."""
        import lance

        lance_path = Path(self.index_root) / f"{self.table_name}.lance"
        if not lance_path.exists():
            return False

        try:
            ds = lance.dataset(str(lance_path))
            versions = sorted(ds.versions(), key=lambda item: item["version"], reverse=True)
        except Exception as exc:
            logger.warning("Cannot inspect Lance versions for recovery: %s", exc)
            return False

        clean_version = None
        for version_info in versions:
            version = version_info["version"]
            try:
                lance.dataset(str(lance_path), version=version).to_table(limit=1)
                clean_version = version
                break
            except Exception:
                continue

        if clean_version is None:
            logger.warning("No readable Lance version found for %s", lance_path)
            return False

        clean_table = lance.dataset(str(lance_path), version=clean_version).to_table()
        corrupt_path = Path(f"{lance_path}.corrupt")
        if corrupt_path.exists():
            shutil.rmtree(corrupt_path)
        shutil.move(str(lance_path), str(corrupt_path))
        lance.write_dataset(clean_table, str(lance_path))
        return True

    def _table_path(self, table_name: str | None = None) -> Path:
        """Return on-disk path for a Lance table."""
        return Path(self.index_root) / f"{table_name or self.table_name}.lance"

    def _reconnect(self) -> None:
        """Reconnect the vector store to the current on-disk table path."""
        self._vs = LanceDBVectorStore(
            uri=self.index_root,
            table_name=self.table_name,
            mode="create",
        )
        self._ensure_scalar_index()

    def _ensure_scalar_index(self) -> None:
        """Create the doc-id BTree once; never replace it on routine opens."""
        try:
            table = self._vs.table
            for index in table.list_indices():
                columns = list(getattr(index, "columns", ()) or ())
                index_type = str(getattr(index, "index_type", "")).upper()
                if columns == ["doc_id"] and index_type == "BTREE":
                    return
            table.create_scalar_index("doc_id", index_type="BTREE", replace=True)
        except TableNotFoundError:
            pass  # Table not created yet on first run
        except Exception as e:
            logger.warning("Failed to create scalar index: %s", e)

    def reset_table(self) -> None:
        """Drop all data for this table so a shadow rebuild starts from a clean slate."""
        table_path = self._table_path()
        if table_path.exists():
            shutil.rmtree(table_path)
        self._reconnect()

    def promote_table(self, shadow_table_name: str) -> None:
        """Atomically replace this table with a prepared shadow table."""
        shadow_path = self._table_path(shadow_table_name)
        active_path = self._table_path()
        backup_path = self._table_path(f"{self.table_name}__backup")

        if not shadow_path.exists():
            raise FileNotFoundError(f"Shadow table does not exist: {shadow_path}")

        if backup_path.exists():
            shutil.rmtree(backup_path)

        active_moved = False
        try:
            if active_path.exists():
                shutil.move(str(active_path), str(backup_path))
                active_moved = True
            shutil.move(str(shadow_path), str(active_path))
        except Exception:
            if active_moved and not active_path.exists() and backup_path.exists():
                shutil.move(str(backup_path), str(active_path))
            raise
        else:
            if backup_path.exists():
                shutil.rmtree(backup_path)
            self._reconnect()
            logger.info("Promoted shadow table %r into %r", shadow_table_name, self.table_name)

    @staticmethod
    def _is_stale_read_error(exc: Exception) -> bool:
        text = str(exc)
        text_lower = text.lower()
        if "not found" not in text_lower:
            return False
        return any(marker in text for marker in _STALE_READ_MARKERS)

    def _reopen_vector_store(self) -> None:
        self._vs = self._build_vector_store()

    def _checkout_latest(self) -> None:
        """Refresh an existing Lance table handle without rebuilding the store."""
        try:
            self._vs.table.checkout_latest()
        except TableNotFoundError:
            pass

    def _run_read_with_recovery(self, operation, default_on_missing):
        try:
            return operation()
        except TableNotFoundError:
            return default_on_missing
        except Exception as exc:
            if not self._is_stale_read_error(exc):
                raise
            logger.warning("Refreshing LanceDB store after stale/corrupt read: %s", exc)
            self._reopen_vector_store()
            try:
                return operation()
            except TableNotFoundError:
                return default_on_missing

    @staticmethod
    def _sql_escape(value: str) -> str:
        """Escape single quotes for safe use in SQL WHERE clauses."""
        return value.replace("'", "''")

    @staticmethod
    def _escape_fts_query(query: str) -> str:
        """Escape natural-language tokens Tantivy misreads as field syntax."""
        return re.sub(r"(?<!\\):", r"\\:", query)

    @staticmethod
    def _is_phrase_query_without_positions(exc: Exception, query: str) -> bool:
        text = str(exc).lower()
        return '"' in query and "position is not found but required for phrase queries" in text

    @staticmethod
    def _strip_phrase_quotes(query: str) -> str:
        return " ".join(query.replace('"', " ").split())

    @staticmethod
    def _validate_identifier(key: str) -> None:
        """Raise ValueError if *key* is not a safe SQL identifier."""
        if not _SAFE_IDENTIFIER_RE.match(key):
            raise ValueError(f"Unsafe metadata filter key: {key!r}")

    def _metadata_field_sql(self, key: str) -> str:
        """Return SQL reference for a metadata field after identifier validation."""
        self._validate_identifier(key)
        return f"metadata.{key}"

    def _build_filter_ast_clause(self, node: dict) -> str:
        """Compile a structured filter AST to a LanceDB SQL WHERE fragment."""
        if not isinstance(node, dict) or len(node) != 1:
            raise ValueError("filter must be an object with exactly one operator")

        op, payload = next(iter(node.items()))
        if op in {"and", "or"}:
            if not isinstance(payload, list) or not payload:
                raise ValueError(f"{op} filter must be a non-empty list")
            joiner = f" {op.upper()} "
            return "(" + joiner.join(self._build_filter_ast_clause(item) for item in payload) + ")"

        if op == "not":
            if not isinstance(payload, dict):
                raise ValueError("not filter must contain one nested filter object")
            return f"NOT ({self._build_filter_ast_clause(payload)})"

        if op not in {"eq", "ne", "contains", "prefix", "in"}:
            raise ValueError(f"Unsupported filter operator: {op}")
        if not isinstance(payload, dict) or len(payload) != 1:
            raise ValueError(f"{op} filter must be an object with exactly one field")

        key, value = next(iter(payload.items()))
        field = self._metadata_field_sql(key)

        if op == "in":
            if not isinstance(value, list) or not value:
                raise ValueError("in filter value must be a non-empty list")
            values = ", ".join(
                f"'{self._sql_escape(str(item).lower())}'"
                for item in value
            )
            return f"lower({field}) IN ({values})"

        escaped = self._sql_escape(str(value))
        escaped_lower = self._sql_escape(str(value).lower())

        if op == "eq":
            return f"lower({field}) = '{escaped_lower}'"
        if op == "ne":
            return f"lower({field}) != '{escaped_lower}'"
        if op == "contains":
            return f"lower({field}) LIKE '%{escaped_lower}%'"
        if op == "prefix":
            if key == "rel_path":
                return f"{field} LIKE '{escaped}%'"
            return f"lower({field}) LIKE '{escaped_lower}%'"

        raise ValueError(f"Unsupported filter operator: {op}")

    def _metadata_subfields(self) -> set[str]:
        """Return the set of sub-field names inside the metadata struct column."""
        def _op():
            ds = self._vs.table.to_lance()
            for field in ds.schema:
                if field.name == "metadata":
                    return {sf.name for sf in field.type}
            return set()

        try:
            return self._run_read_with_recovery(_op, set())
        except Exception:
            return set()

    def _evolve_metadata_schema(self, new_fields: set[str]) -> None:
        """Add new string sub-fields to the metadata struct column.

        Reads the entire table as Arrow, adds empty-string columns for each
        new field, reconstructs the metadata struct, and replaces the table.
        """
        import lancedb as ldb

        table = self._vs.table
        arrow_table = table.to_arrow()

        # Extract existing metadata struct arrays
        meta_chunked = arrow_table.column("metadata")
        meta_col = meta_chunked.combine_chunks()  # StructArray (not ChunkedArray)
        meta_type = meta_col.type
        existing_names = [meta_type.field(i).name for i in range(meta_type.num_fields)]

        # Build new struct arrays: existing + new fields filled with ""
        n_rows = len(arrow_table)
        arrays = [meta_col.field(name) for name in existing_names]
        fields = [meta_type.field(i) for i in range(meta_type.num_fields)]

        for fname in sorted(new_fields):
            if fname not in existing_names:
                arrays.append(pa.array([""] * n_rows, type=pa.utf8()))
                fields.append(pa.field(fname, pa.utf8()))

        new_struct = pa.StructArray.from_arrays(arrays, fields=fields)

        # Replace metadata column in the table
        col_idx = arrow_table.schema.get_field_index("metadata")
        new_arrow = arrow_table.set_column(col_idx, pa.field("metadata", new_struct.type), new_struct)

        db = ldb.connect(self.index_root)
        temp_name = f"{self.table_name}__schema_tmp"
        backup_name = f"{self.table_name}__schema_backup"
        temp_path = Path(self.index_root) / f"{temp_name}.lance"
        table_path = Path(self.index_root) / f"{self.table_name}.lance"
        backup_path = Path(self.index_root) / f"{backup_name}.lance"

        def _table_names() -> set[str]:
            try:
                result = db.list_tables()
                names = getattr(result, "tables", result)
                return set(names)
            except AttributeError:
                return set(db.table_names())

        for stale in (temp_name, backup_name):
            if stale in _table_names():
                db.drop_table(stale)
        for stale_path in (temp_path, backup_path):
            if stale_path.exists():
                shutil.rmtree(stale_path)

        backup_created = False
        try:
            try:
                db.create_table(temp_name, new_arrow)
            except Exception:
                if temp_path.exists():
                    shutil.rmtree(temp_path)
                raise

            shutil.move(str(table_path), str(backup_path))
            backup_created = True
            shutil.move(str(temp_path), str(table_path))
        except Exception:
            if backup_created and not table_path.exists() and backup_path.exists():
                try:
                    shutil.move(str(backup_path), str(table_path))
                except Exception:
                    logger.exception("Failed to restore %s after schema evolution failure", self.table_name)
            raise
        else:
            if backup_path.exists():
                shutil.rmtree(backup_path)
        finally:
            if temp_path.exists():
                shutil.rmtree(temp_path)

        # Reconnect LanceDBVectorStore to the new table
        self._vs = LanceDBVectorStore(
            uri=self.index_root,
            table_name=self.table_name,
            mode="create",
        )
        self._ensure_scalar_index()
        logger.info("Schema evolved: added metadata fields %s", new_fields)

    # --- WHERE clause builder ---

    def _build_where_clause(
        self,
        doc_id_prefix: str | None = None,
        source_type: str | None = None,
        source_name: str | None = None,
        status: str | None = None,
        folder: str | None = None,
        tags: str | None = None,
        enr_doc_type: str | None = None,
        enr_topics: str | None = None,
        metadata_filters: dict[str, str] | None = None,
        filter_ast: dict | None = None,
    ) -> str | None:
        """Build a SQL WHERE clause from filter parameters for LanceDB prefilter.

        Returns None if no filters are active.
        """
        parts: list[str] = []

        # Exact match on metadata fields (case-insensitive)
        if source_type:
            parts.append(f"lower(metadata.source_type) = '{self._sql_escape(source_type.lower())}'")
        if source_name:
            parts.append(f"lower(metadata.source_name) = '{self._sql_escape(source_name.lower())}'")
        if status:
            parts.append(f"lower(metadata.status) = '{self._sql_escape(status.lower())}'")
        if folder:
            parts.append(f"lower(metadata.folder) = '{self._sql_escape(folder.lower())}'")

        # Prefix match on rel_path metadata field (case-sensitive — paths)
        # doc_id is now a persistent 5-char ID; path-based browsing uses rel_path
        if doc_id_prefix:
            parts.append(f"metadata.rel_path LIKE '{self._sql_escape(doc_id_prefix)}%'")

        # Comma-separated OR fields (tags, enr_doc_type, enr_topics) — case-insensitive
        for field, value in [
            ("tags", tags),
            ("enr_doc_type", enr_doc_type),
            ("enr_topics", enr_topics),
        ]:
            if value:
                items = [item.strip() for item in value.split(",") if item.strip()]
                if items:
                    or_parts = [
                        f"lower(metadata.{field}) LIKE '%{self._sql_escape(item.lower())}%'"
                        for item in items
                    ]
                    parts.append(f"({' OR '.join(or_parts)})")

        # Arbitrary metadata key=value pairs (case-insensitive)
        if metadata_filters:
            for key, val in metadata_filters.items():
                self._validate_identifier(key)
                parts.append(f"lower(metadata.{key}) = '{self._sql_escape(str(val).lower())}'")

        if filter_ast is not None:
            parts.append(self._build_filter_ast_clause(filter_ast))

        return " AND ".join(parts) if parts else None

    # --- Shared row-to-hit converter ---

    @staticmethod
    def _row_to_hit(row: dict) -> "SearchHit":
        """Convert a raw LanceDB row dict to a SearchHit.

        Handles both vector search (_distance → similarity) and FTS (_score).
        """
        meta = row.get("metadata") if isinstance(row.get("metadata"), dict) else {}
        text = row.get("text", "") or ""

        doc_id = (
            meta.get("doc_id")
            or row.get("doc_id")
            or row.get("_node_ref_doc_id", "")
        )
        loc = meta.get("loc") or row.get("loc", "")
        snippet = meta.get("snippet") or text[:200]

        # Score: vector search returns _distance (cosine), FTS returns _score
        if "_distance" in row:
            score = 1.0 - float(row["_distance"])
        elif "_score" in row:
            score = float(row["_score"])
        elif "score" in row:
            score = float(row["score"])
        else:
            score = 0.0

        raw_mtime = meta.get("mtime") or row.get("mtime") or 0.0
        combined_meta = {**row, **meta} if meta else row

        return SearchHit(
            doc_id=doc_id,
            loc=loc,
            snippet=snippet,
            text=text,
            score=score,
            source_type=meta.get("source_type") or row.get("source_type"),
            title=meta.get("title") or row.get("title"),
            tags=meta.get("tags") or row.get("tags"),
            folder=meta.get("folder") or row.get("folder"),
            status=meta.get("status") or row.get("status"),
            created=meta.get("created") or row.get("created"),
            mtime=float(raw_mtime) if raw_mtime else 0.0,
            rel_path=meta.get("rel_path") or row.get("rel_path", ""),
            **_extract_enrichment(combined_meta),
            extra_metadata=_extract_extra_metadata(meta),
            vector=row.get("vector"),
        )

    # --- StorageInterface methods ---

    def upsert_nodes(self, nodes: list[TextNode]) -> None:
        """Replace each document while excluding peer writers."""
        doc_ids = {n.ref_doc_id for n in nodes if n.ref_doc_id}
        with self._serialize_document_writes(doc_ids):
            if not self._exclusive_writer_depth:
                self._checkout_latest()
            self._write_nodes_unlocked(nodes, operation="upsert")

    def insert_nodes(
        self, nodes: list[TextNode], *, known_absent: bool = False
    ) -> None:
        """Insert documents once, avoiding delete-only transactions.

        Full sweeps pass ``known_absent=True`` while holding the table-level
        writer session; their authoritative pre-run snapshot therefore needs
        no per-document Lance refresh. Standalone callers retain a fresh
        existence probe under the document lock.
        """
        doc_ids = {n.ref_doc_id for n in nodes if n.ref_doc_id}
        with self._serialize_document_writes(doc_ids):
            existing_doc_ids = doc_ids & self._completed_insert_doc_ids
            if not known_absent and not self._exclusive_writer_depth:
                # A standalone caller has no table-level session proving its
                # snapshot remains current. Probe a fresh, short-lived dataset
                # while the document lock excludes peer writers.
                with self._measure_memory("storage_insert_probe"):
                    existing_doc_ids.update(
                        doc_id
                        for doc_id in doc_ids - existing_doc_ids
                        if self._contains_doc_id_latest(doc_id)
                    )
            nodes_to_insert = [
                node
                for node in nodes
                if not node.ref_doc_id or node.ref_doc_id not in existing_doc_ids
            ]
            if not nodes_to_insert:
                logger.info(
                    "Skipped insert for documents already present: %s",
                    sorted(existing_doc_ids),
                )
                return
            inserted_doc_ids = {
                node.ref_doc_id for node in nodes_to_insert if node.ref_doc_id
            }
            try:
                self._write_nodes_unlocked(nodes_to_insert, operation="insert")
            except Exception:
                # Lance commits atomically, but a transport/runtime failure can
                # be reported after the commit. Probe only this exceptional
                # path so a Prefect retry cannot append the same document.
                with self._measure_memory("storage_insert_recovery_probe"):
                    committed = {
                        doc_id
                        for doc_id in inserted_doc_ids
                        if self._contains_doc_id_latest(doc_id)
                    }
                if inserted_doc_ids and committed == inserted_doc_ids:
                    self._completed_insert_doc_ids.update(committed)
                    logger.warning(
                        "Insert raised after commit for doc_ids=%s; treating as complete",
                        sorted(committed),
                    )
                    return
                raise
            self._completed_insert_doc_ids.update(inserted_doc_ids)

    def _write_nodes_unlocked(
        self, nodes: list[TextNode], *, operation: str
    ) -> None:
        """Write nodes, deleting prior chunks only for replacement updates."""
        delete_existing = operation == "upsert"
        with _tracer.start_as_current_span(f"store.{operation}"):
            if not nodes:
                return

            # Defense in depth (#0108): metadata that came from a read-back row
            # carries LlamaIndex-managed keys; persisting them nests the stale
            # _node_content inside the fresh serialization and it compounds on
            # every rewrite. All of these are regenerated at write time.
            for n in nodes:
                if n.metadata and not _LLAMA_MANAGED_METADATA_KEYS.isdisjoint(n.metadata):
                    n.metadata = _strip_llama_managed_keys(n.metadata)

            # Collect distinct doc_ids from this batch
            doc_ids = {n.ref_doc_id for n in nodes if n.ref_doc_id}
            memory_fields: dict[str, Any]
            if len(doc_ids) == 1:
                memory_fields = {"doc_id": next(iter(doc_ids))}
            else:
                memory_fields = {"doc_ids": sorted(doc_ids)}

            # Detect new metadata fields and evolve schema if needed
            with self._measure_memory("storage_schema", **memory_fields):
                existing_subfields = self._metadata_subfields()
                if existing_subfields:  # table already has data
                    incoming_keys: set[str] = set()
                    for n in nodes:
                        if n.metadata:
                            incoming_keys.update(n.metadata.keys())
                    if incoming_keys:
                        # Threaded indexing shares one store instance; re-check missing
                        # fields under a lock so temp-table schema evolution is serialized.
                        with self._schema_lock:
                            existing_subfields = self._metadata_subfields()
                            new_fields = incoming_keys - existing_subfields
                            if new_fields:
                                self._evolve_metadata_schema(new_fields)

            # New documents are proven absent by the flow diff. Avoid a no-op
            # delete: Lance commits it as a full metadata version anyway, so a
            # large insert batch otherwise doubles manifests and retained
            # transaction state before final pruning.
            if delete_existing:
                with self._measure_memory("storage_delete", **memory_fields):
                    for doc_id in doc_ids:
                        try:
                            self._vs.delete(doc_id)
                        except TableNotFoundError:
                            pass  # Table not created yet on first run
                        except Exception as e:
                            logger.warning("Failed to delete old data for %s: %s", doc_id, e)
                            continue
                        self._completed_insert_doc_ids.discard(doc_id)
            # Add new nodes
            try:
                with self._measure_memory("storage_add", **memory_fields):
                    self._vs.add(nodes)
            except Exception:
                if delete_existing:
                    logger.critical(
                        "Failed to add %d nodes for doc_ids=%s after old chunks were deleted; "
                        "these docs will self-heal on the next index run",
                        len(nodes), sorted(doc_ids),
                    )
                else:
                    logger.critical(
                        "Failed to insert %d nodes for doc_ids=%s; "
                        "these docs will self-heal on the next index run",
                        len(nodes), sorted(doc_ids),
                    )
                raise

    def _load_unique_canonical_rows(
        self, table: Any, canonical_doc_id: str
    ) -> tuple[list[dict[str, Any]], int]:
        """Load at most one full row per chunk id, never every physical duplicate."""
        escaped_doc_id = self._sql_escape(canonical_doc_id)
        batches = (
            table.to_lance()
            .sql(
                "SELECT DISTINCT id FROM dataset "
                f"WHERE doc_id = '{escaped_doc_id}' AND id IS NOT NULL"
            )
            .build()
            .to_batch_records()
        )
        unique_chunk_ids = (
            pa.Table.from_batches(batches)["id"].to_pylist() if batches else []
        )
        rows: list[dict[str, Any]] = []
        for chunk_id in sorted(str(value) for value in unique_chunk_ids if value):
            escaped_chunk_id = self._sql_escape(chunk_id)
            row = (
                table.search(None)
                .where(
                    f"doc_id = '{escaped_doc_id}' AND id = '{escaped_chunk_id}'",
                    prefilter=True,
                )
                .select(["id", "doc_id", "text", "vector", "metadata"])
                .limit(1)
                .to_list()
            )
            if row:
                rows.append(row[0])
        return rows, table.count_rows(f"doc_id = '{escaped_doc_id}'")

    def update_canonical_duplicate_metadata(
        self,
        canonical_doc_id: str,
        duplicate_refs: list[dict[str, Any]],
    ) -> None:
        """Single-flight canonical metadata rewrites by canonical document."""
        with self._serialize_document_writes([canonical_doc_id]):
            self._checkout_latest()
            self._update_canonical_duplicate_metadata_unlocked(
                canonical_doc_id, duplicate_refs
            )

    def _update_canonical_duplicate_metadata_unlocked(
        self,
        canonical_doc_id: str,
        duplicate_refs: list[dict[str, Any]],
    ) -> None:
        """Merge duplicate provenance into canonical chunk metadata and re-upsert it."""
        try:
            table = self._vs.table
        except TableNotFoundError as exc:
            raise LookupError(
                f"Canonical doc {canonical_doc_id} missing in LanceDB; refusing duplicate metadata update"
            ) from exc

        with self._measure_memory("storage_canonical_read", doc_id=canonical_doc_id):
            rows, physical_rows = self._load_unique_canonical_rows(
                table, canonical_doc_id
            )
        if not rows:
            raise LookupError(
                f"Canonical doc {canonical_doc_id} missing in LanceDB; refusing duplicate metadata update"
            )
        if physical_rows > len(rows):
            logger.warning(
                "Compacting duplicate canonical rows for %s: %d physical rows, %d unique chunk ids",
                canonical_doc_id,
                physical_rows,
                len(rows),
            )

        first_meta = rows[0].get("metadata") if isinstance(rows[0].get("metadata"), dict) else {}
        dup_sources = _json_string_list(first_meta.get("dup_sources"))
        dup_locations = _json_string_list(first_meta.get("dup_locations"))
        dup_archive_paths = _json_string_list(first_meta.get("dup_archive_paths"))
        dup_natural_keys = _json_string_list(first_meta.get("dup_natural_keys"))

        seen_duplicates: set[tuple[str, str, str, str, str]] = set()
        for duplicate_ref in duplicate_refs:
            natural_key = _duplicate_natural_key(duplicate_ref)
            duplicate_key = (
                str(duplicate_ref.get("doc_id") or "").strip(),
                str(duplicate_ref.get("source_name") or "").strip(),
                str(duplicate_ref.get("rel_path") or "").strip(),
                str(duplicate_ref.get("archive_path") or "").strip(),
                natural_key,
            )
            if duplicate_key in seen_duplicates:
                continue
            seen_duplicates.add(duplicate_key)
            _append_unique(dup_sources, duplicate_ref.get("source_name"))
            _append_unique(dup_locations, duplicate_ref.get("rel_path"))
            _append_unique(dup_archive_paths, duplicate_ref.get("archive_path"))
            _append_unique(dup_natural_keys, natural_key)

        existing_dup_count = str(first_meta.get("dup_count") or "").strip()
        try:
            prior_dup_count = int(existing_dup_count)
        except ValueError:
            prior_dup_count = 0
        merged_dup_count = max(
            prior_dup_count,
            len(seen_duplicates),
            len(dup_locations),
            len(dup_archive_paths),
            len(dup_natural_keys),
        )
        duplicate_metadata = {
            "dup_count": str(merged_dup_count),
            "dup_sources": json.dumps(dup_sources),
            "dup_locations": json.dumps(dup_locations),
            "dup_archive_paths": json.dumps(dup_archive_paths),
            "dup_natural_keys": json.dumps(dup_natural_keys),
        }

        canonical_nodes: list[TextNode] = []
        for row in rows:
            metadata = row.get("metadata") if isinstance(row.get("metadata"), dict) else {}
            metadata = _strip_llama_managed_keys(metadata)
            vector = row.get("vector")
            if hasattr(vector, "tolist"):
                vector = vector.tolist()
            elif vector is None:
                vector = []
            else:
                vector = list(vector)
            loc = metadata.get("loc") or ""
            node = TextNode(
                text=row.get("text", "") or "",
                id_=row.get("id") or f"{canonical_doc_id}::{loc}",
                embedding=vector,
                metadata={**metadata, **duplicate_metadata},
            )
            node.relationships[NodeRelationship.SOURCE] = RelatedNodeInfo(node_id=canonical_doc_id)
            canonical_nodes.append(node)

        self._write_nodes_unlocked(canonical_nodes, operation="upsert")

    def delete_by_doc_ids(self, doc_ids: list[str]) -> None:
        """Remove documents without racing a concurrent rewrite of the same IDs."""
        with self._serialize_document_writes(doc_ids):
            if not self._exclusive_writer_depth:
                self._checkout_latest()
            self._delete_by_doc_ids_unlocked(doc_ids)

    def _delete_by_doc_ids_unlocked(self, doc_ids: list[str]) -> None:
        """Remove all nodes; report failure after attempting every document."""
        memory_fields: dict[str, Any]
        if len(doc_ids) == 1:
            memory_fields = {"doc_id": doc_ids[0]}
        else:
            memory_fields = {"doc_ids": list(doc_ids)}
        first_error: Exception | None = None
        with self._measure_memory("storage_delete", **memory_fields):
            for doc_id in doc_ids:
                try:
                    self._vs.delete(doc_id)
                except TableNotFoundError:
                    pass  # Table not created yet — nothing to delete
                except Exception as e:
                    logger.warning("Failed to delete doc %s: %s", doc_id, e)
                    if first_error is None:
                        first_error = e
                    continue
                self._completed_insert_doc_ids.discard(doc_id)
        if first_error is not None:
            raise first_error

    def list_doc_ids(self) -> list[str]:
        """Return all distinct doc_ids in the store.

        Uses Lance SQL DISTINCT — reads only the doc_id column, no vectors or text.
        Raises on failure so callers get a proper error (not empty results).
        """
        def _op():
            ds = self._vs.table.to_lance()
            batches = ds.sql("SELECT DISTINCT doc_id FROM dataset WHERE doc_id IS NOT NULL").build().to_batch_records()
            if not batches:
                return []
            return pa.Table.from_batches(batches)["doc_id"].to_pylist()

        return self._run_read_with_recovery(_op, [])

    def contains_doc_id(self, doc_id: str) -> bool:
        """Return whether at least one physical row exists for ``doc_id``."""
        escaped_doc_id = self._sql_escape(doc_id)

        def _op():
            return self._vs.table.count_rows(f"doc_id = '{escaped_doc_id}'") > 0

        return self._run_read_with_recovery(_op, False)

    def _contains_doc_id_latest(self, doc_id: str) -> bool:
        """Probe the latest manifest without mutating the long-lived writer handle."""
        table_path = self._table_path()
        if not table_path.exists():
            return False

        import lance

        escaped_doc_id = self._sql_escape(doc_id)
        dataset = lance.dataset(str(table_path))
        return dataset.count_rows(f"doc_id = '{escaped_doc_id}'") > 0

    def list_doc_mtimes(self) -> dict[str, float]:
        """Return {doc_id: mtime} for all docs in the store.

        Projects ONLY doc_id + metadata.mtime and aggregates in Python. A SQL
        GROUP BY over metadata.* decodes the whole metadata struct, whose large
        enrichment string subfields can exceed Arrow's 2 GB per-column offset
        limit on a big index (LanceError: Offset overflow). Reading just the
        two needed columns sidesteps that entirely.
        """
        def _op():
            ds = self._vs.table.to_lance()
            t = ds.to_table(columns={"doc_id": "doc_id", "mtime": "metadata.mtime"})
            ids = t["doc_id"].to_pylist()
            mts = t["mtime"].to_pylist()
            out: dict[str, float] = {}
            for d, m in zip(ids, mts):
                if d is None:
                    continue
                v = float(m) if m is not None else 0.0
                if d not in out or v > out[d]:
                    out[d] = v
            return out

        return self._run_read_with_recovery(_op, {})

    def list_doc_change_hashes(self) -> dict[str, str]:
        """Return {doc_id: change_hash} for content-hash change detection.

        Returns {} if no doc carries a change_hash yet (old index, or before any
        hash-aware run) — callers then fall back to mtime comparison.
        """
        if "change_hash" not in self._metadata_subfields():
            return {}

        def _op():
            ds = self._vs.table.to_lance()
            t = ds.to_table(columns={"doc_id": "doc_id", "ch": "metadata.change_hash"})
            ids = t["doc_id"].to_pylist()
            hashes = t["ch"].to_pylist()
            out: dict[str, str] = {}
            for d, h in zip(ids, hashes):
                if d is not None:
                    out[d] = h or ""
            return out

        return self._run_read_with_recovery(_op, {})

    def count_chunks(self) -> int:
        """Return total number of chunks (rows) in the store. O(1) via LanceDB.

        Raises on failure so callers get a proper error (not zero).
        """
        return self._run_read_with_recovery(lambda: self._vs.table.count_rows(), 0)

    def vector_search(
        self,
        query_vector: list[float],
        top_k: int,
        where: str | None = None,
        include_vector: bool = True,
    ) -> list[SearchHit]:
        """Vector search via direct LanceDB query with optional prefilter.

        Raises on failure so the caller (hybrid_search) can track degradation.
        """
        def _op():
            q = self._vs.table.search(query_vector, query_type="vector")
            if where:
                q = q.where(where, prefilter=True)
            rows = q.limit(top_k).to_list()
            if not include_vector:
                for row in rows:
                    row.pop("vector", None)
            return [self._row_to_hit(row) for row in rows]

        return self._run_read_with_recovery(_op, [])

    # --- Full-Text Search (BM25, Lance-native inverted index) ---

    def create_fts_index(self) -> None:
        """Create or fully rebuild the native FTS index on the text column.

        The Lance-native index updates incrementally — rows added after index
        creation are searchable immediately and deletes are respected without
        a rebuild. A full rebuild is only needed for first-time creation and
        recovery paths; routine indexing runs should call ensure_fts_index().
        Raises on failure so the caller can track the error.
        """
        table = self._vs.table
        text_key = getattr(self._vs, "text_key", "text")
        table.create_fts_index(text_key, use_tantivy=False, replace=True)
        logger.info("FTS index created/rebuilt on column %r", text_key)

    def ensure_fts_index(self, *, compact_data: bool = True) -> None:
        """Make sure the native FTS index exists and is optimized.

        Creates the index if missing; otherwise merges newly written rows into
        the existing index via optimize(). Unindexed rows are still searchable
        before the merge, so this is a performance step, not a correctness one.
        Raises on failure so the caller can track the error.
        """
        table = self._vs.table
        text_key = getattr(self._vs, "text_key", "text")
        has_fts = any(
            str(getattr(idx, "index_type", "")).upper() == "FTS"
            for idx in table.list_indices()
        )
        if not has_fts:
            if compact_data:
                self.prepare_indexing_maintenance()
                table = self._vs.table
            table.create_fts_index(text_key, use_tantivy=False)
            logger.info("FTS index created on column %r", text_key)
            from datetime import date

            self._finish_index_maintenance(table, date.today())
            return
        self._optimize_and_prune(table, compact_data=compact_data)
        logger.info("FTS index optimized (incremental merge)")

    def prepare_indexing_maintenance(self) -> bool:
        """Run due data compaction before a memory-heavy indexing phase.

        Flows that will process documents call this against an existing table
        before allocating document-processing state. Finalization can then
        merge index deltas and refresh restore points without overlapping the
        daily full-table rewrite with that state.
        """
        from datetime import date

        self._prune_versions("pre-maintenance")
        return self._compact_data_files_if_due(date.today())

    def _optimize_and_prune(self, table, *, compact_data: bool = True) -> None:
        """Merge index deltas, refresh restore points, and prune old versions.

        ``compact_data`` preserves the all-in-one behavior for ordinary callers.
        Indexing flows that already attempted pre-processing maintenance disable
        it here so a failed compaction is not retried while processing state is
        still resident.

        Full data compaction rewrites every fragment, and each
        retained daily restore-point tag pins the superseded fragments until
        that tag expires — running it every ~15-minute indexing cycle held a
        full rewrite of the table per cycle per tag on disk and grew a ~5 GB
        table to 350+ GB of dead files (#0232). Compaction is therefore
        bounded to once per calendar day, tracked by a plain-text marker
        outside the dataset (atomic replace; survives restarts without
        pinning any Lance version). Every other run only merges newly written
        rows into the search indices (optimize_indices — no data rewrite).

        Ordering matters: prune -> compact/merge -> tag today -> expire tags
        -> prune. The first prune frees headroom before any rewrite; the
        second reclaims versions unpinned by tag expiry in the same run.
        The prunes run via dataset-level cleanup_old_versions with
        error_if_tagged_old_versions=False so tagged restore points are
        skipped, not errors (and delete_unverified stays False — Lance's
        in-flight-write protection is only overridden in stopped-service
        repair, never routinely).

        Compaction, tagging, and pruning are housekeeping: failures are logged,
        never raised. A failed compaction leaves the marker unwritten for a
        later run. Only the index-delta merge propagates, letting the flow fall
        back to a full FTS rebuild.
        """
        from datetime import date

        today = date.today()
        if compact_data:
            self._prune_versions("pre-maintenance")
            self._compact_data_files_if_due(today)

        self._merge_index_deltas()
        self._finish_index_maintenance(table, today)

    def _finish_index_maintenance(self, table, today) -> None:
        """Stage a safe tag, expire/prune, then retag exact latest."""
        if not self._tag_latest_restore_point(table, today):
            return
        self._expire_restore_points(table, today)
        self._prune_versions("post-expiry")
        self._tag_latest_restore_point(table, today)

    def _compact_data_files_if_due(self, today) -> bool:
        """Best-effort daily data compaction with durable success cadence."""
        if not self._compaction_due(today):
            return False

        from core.resilience import call_with_retry

        try:
            call_with_retry(
                self._compact_data_files,
                attempts=3,
                backoff=(2.0, 5.0),
                label="lance daily compaction",
                classify=_is_retryable_commit_conflict,
            )
        except Exception as exc:
            logger.warning(
                "Daily Lance compaction failed (%s); retrying next run", exc
            )
            return False

        self._record_compaction(today)
        # The child committed a new manifest using an independent Lance
        # session. Refresh the parent's one stable handle exactly once before
        # any write, merge, or restore-point operation uses it.
        self._checkout_latest()
        return True

    def _compact_data_files(self) -> None:
        """Compact in a worker whose native allocations are released on exit."""
        with self._measure_memory("lance_daily_compaction"):
            command = [
                sys.executable,
                "-m",
                "core.lance_maintenance",
                "compact",
                self._dataset_path(),
            ]
            try:
                subprocess.run(
                    command,
                    check=True,
                    capture_output=True,
                    close_fds=True,
                    text=True,
                )
            except subprocess.CalledProcessError as exc:
                detail = (exc.stderr or exc.stdout or str(exc)).strip()
                raise RuntimeError(
                    f"Lance compaction worker failed: {detail}"
                ) from exc

    def _dataset_path(self) -> str:
        return str(Path(self.index_root) / f"{self.table_name}.lance")

    def _compaction_marker_path(self) -> Path:
        # Lives NEXT TO the .lance directory, not inside it — Lance owns that
        # tree and cleanup may remove files it does not recognize.
        return Path(self.index_root) / (
            f"{self.table_name}.lance{_COMPACTION_MARKER_SUFFIX}"
        )

    def _compaction_due(self, today) -> bool:
        from datetime import date

        try:
            recorded = self._compaction_marker_path().read_text().strip()
            return date.fromisoformat(recorded) < today
        except (OSError, ValueError):
            # Missing or unreadable marker: compact now and rewrite it.
            return True

    def _record_compaction(self, today) -> None:
        """Write-then-rename so a crash mid-write cannot corrupt the marker."""
        marker = self._compaction_marker_path()
        tmp = marker.with_name(marker.name + ".tmp")
        try:
            tmp.write_text(today.isoformat())
            os.replace(tmp, marker)
        except OSError as exc:
            logger.warning("Could not record compaction date: %s", exc)

    def _merge_index_deltas(self) -> None:
        """Merge newly written rows into the existing indices without
        rewriting data files. Raises on failure so the flow can fall back to
        a full FTS rebuild."""
        import lance

        lance.dataset(self._dataset_path()).optimize.optimize_indices()

    def _prune_versions(self, label: str) -> None:
        """Reclaim superseded, untagged Lance versions older than the
        retention band, logging reclaimed bytes/files so shrinkage (or its
        absence) is observable. Best-effort: failure is logged, never raised
        (dead versions reclaim on a later pass)."""
        from datetime import timedelta

        from core.resilience import call_with_retry

        retention = timedelta(minutes=_lance_version_retention_minutes())
        try:
            import lance

            def _prune():
                return lance.dataset(self._dataset_path()).cleanup_old_versions(
                    older_than=retention,
                    error_if_tagged_old_versions=False,
                )

            stats = call_with_retry(
                _prune,
                attempts=3,
                backoff=(2.0, 5.0),
                label=f"lance version prune ({label})",
                classify=_is_retryable_commit_conflict,
            )
            if stats is not None and stats.old_versions:
                logger.info(
                    "Lance version prune (%s): reclaimed %d bytes "
                    "(%d versions, %d data files)",
                    label,
                    stats.bytes_removed,
                    stats.old_versions,
                    stats.data_files_removed,
                )
        except Exception as exc:
            logger.warning(
                "Version prune (%s) failed (%s); dead versions reclaim next run",
                label,
                exc,
            )

    def _manage_restore_points(self, table, today) -> None:
        """Keep exactly N daily version tags (today plus N-1 prior days) as
        logical restore points.

        Compatibility wrapper for callers outside the indexing finalizer. The
        finalizer stages today's tag before destructive work, expires old
        tags, prunes, then retags because cleanup can commit a metadata-only
        Lance version.
        """
        if not self._tag_latest_restore_point(table, today):
            return
        self._expire_restore_points(table, today)

    def _expire_restore_points(self, table, today) -> None:
        """Drop expired daily tags before pruning; never touch manual tags."""
        days = _daily_restore_point_days()
        try:
            table.checkout_latest()
            tags = table.tags
            existing = set(tags.list())

            if days <= 0:
                for tag_name in existing:
                    if _parse_daily_tag_date(tag_name) is not None:
                        tags.delete(tag_name)
                return

            from datetime import timedelta

            cutoff = today - timedelta(days=days - 1)
            for tag_name in existing:
                tag_date = _parse_daily_tag_date(tag_name)
                if tag_date is not None and tag_date < cutoff:
                    tags.delete(tag_name)
        except Exception as exc:
            logger.warning("Daily restore-point expiry skipped this run: %s", exc)

    def _tag_latest_restore_point(self, table, today) -> bool:
        """Pin latest state, returning false when destructive work must stop."""
        if _daily_restore_point_days() <= 0:
            return True
        try:
            # Tag the true latest version, not a stale cached one — a tag on
            # an old version pins its superseded data files (#0232).
            table.checkout_latest()
            tags = table.tags
            existing = set(tags.list())
            name = _daily_tag_name(today)
            version = table.version
            if name in existing:
                tags.update(name, version)
            else:
                tags.create(name, version)
            return True
        except Exception as exc:
            logger.warning("Daily restore-point tagging skipped this run: %s", exc)
            return False

    def fts_available(self) -> bool:
        """Check if the FTS/tantivy index is operational (health check for file_status)."""
        try:
            self._run_read_with_recovery(
                lambda: self._vs.table.search("test", query_type="fts").limit(1).to_list(),
                [],
            )
            return True
        except Exception:
            return False

    def keyword_search(
        self,
        query: str,
        top_k: int = 50,
        where: str | None = None,
        include_vector: bool = True,
    ) -> list[SearchHit]:
        """BM25/FTS keyword search via LanceDB tantivy index with optional prefilter.

        Returns SearchHit list ranked by BM25 relevance. Raises on FTS failure
        so the caller (hybrid_search) can track degradation in diagnostics.
        """
        if not query.strip():
            return []

        def _search_rows(fts_query: str):
            q = self._vs.table.search(fts_query, query_type="fts")
            if where:
                q = q.where(where, prefilter=True)
            return q.limit(top_k).to_list()

        def _op():
            try:
                rows = _search_rows(self._escape_fts_query(query))
            except Exception as exc:
                if not self._is_phrase_query_without_positions(exc, query):
                    raise
                fallback_query = self._strip_phrase_quotes(query)
                if not fallback_query:
                    raise
                logger.warning(
                    "FTS phrase query unsupported without positions; retrying without quotes: %r",
                    query,
                )
                rows = _search_rows(self._escape_fts_query(fallback_query))
            if not include_vector:
                for row in rows:
                    row.pop("vector", None)
            return [self._row_to_hit(row) for row in rows]

        return self._run_read_with_recovery(_op, [])

    _RECENT_DOC_FIELDS = (
        "title",
        "source_type",
        "folder",
        "tags",
        "status",
        "created",
        "keywords",
        *_DUPLICATE_META_FIELDS,
    )

    def list_recent_docs(
        self,
        limit: int = 20,
        source_type: str | None = None,
        folder: str | None = None,
    ) -> list[dict]:
        """Return recently modified docs sorted by mtime descending.

        Uses Lance SQL with GROUP BY, ORDER BY, and LIMIT — all server-side.
        No vectors or text loaded. Raises on failure so callers get a proper error.
        """
        def _op():
            ds = self._vs.table.to_lance()
            available = self._metadata_subfields()

            where_parts: list[str] = ["doc_id IS NOT NULL"]
            if source_type and "source_type" in available:
                where_parts.append(f"metadata.source_type = '{self._sql_escape(source_type)}'")
            if folder and "folder" in available:
                where_parts.append(f"metadata.folder = '{self._sql_escape(folder)}'")
            where_clause = " AND ".join(where_parts)

            # Build SELECT with only fields that exist in the metadata struct
            select_parts = ["doc_id"]
            output_fields = ["doc_id"]
            if "mtime" in available:
                select_parts.append("MAX(metadata.mtime) AS mtime")
                output_fields.append("mtime")
            for f in self._RECENT_DOC_FIELDS:
                if f in available:
                    select_parts.append(f"MAX(metadata.{f}) AS {f}")
                    output_fields.append(f)

            sql = (
                f"SELECT {', '.join(select_parts)} "
                f"FROM dataset WHERE {where_clause} "
                "GROUP BY doc_id "
                f"ORDER BY mtime DESC LIMIT {limit}"
            )
            batches = ds.sql(sql).build().to_batch_records()
            if not batches:
                return []
            t = pa.Table.from_batches(batches)
            result: list[dict] = []
            for i in range(len(t)):
                rec: dict = {}
                for f in output_fields:
                    try:
                        rec[f] = t[f][i].as_py()
                    except (KeyError, IndexError):
                        rec[f] = None
                result.append(rec)
            return result

        return self._run_read_with_recovery(_op, [])

    _FACET_KEY_MAP = {
        "folder": "folders",
        "source_type": "source_types",
        "status": "statuses",
        "enr_doc_type": "doc_types",
        "author": "authors",
        "enr_topics": "topics",
        "enr_keywords": "keywords",
        "enr_entities_people": "entities_people",
        "enr_entities_places": "entities_places",
        "enr_entities_orgs": "entities_orgs",
    }

    # Metadata fields that should NOT be faceted (structural/numeric, not categorical)
    _NON_FACET_FIELDS = {"doc_id", "loc", "snippet", "mtime", "size", "title", "created"}
    _SAFE_CONTEXT_FACET_FIELDS = {"enr_context_confidence"}
    _FACET_SCAN_BATCH_SIZE = 1024
    _DYNAMIC_NON_FACET_FIELDS = {
        "body",
        "content",
        "custom_meta",
        "date",
        "description",
        "dimensions",
        "facts",
        "filename",
        "hash",
        "id",
        "ids",
        "json",
        "modified",
        "narrative",
        "path",
        "summary",
        "text",
        "timestamp",
        "updated",
        "uri",
        "url",
        "warning",
    }
    _DYNAMIC_NON_FACET_SUFFIXES = (
        "_at",
        "_body",
        "_bytes",
        "_content",
        "_description",
        "_facts",
        "_filename",
        "_hash",
        "_id",
        "_ids",
        "_json",
        "_narrative",
        "_path",
        "_summary",
        "_text",
        "_timestamp",
        "_uri",
        "_url",
        "_warning",
    )

    @classmethod
    def _dynamic_facet_fields(cls, available: set[str]) -> set[str]:
        """Return dynamic metadata fields safe to comma-split into facets."""
        all_facet_fields = set(cls._FACET_KEY_MAP.keys())
        candidates = available - all_facet_fields - cls._NON_FACET_FIELDS - {"tags"}
        return {
            field
            for field in candidates
            if (
                not field.startswith("_")
                and not field.startswith("dup_")
                and field not in cls._DYNAMIC_NON_FACET_FIELDS
                and not field.endswith(cls._DYNAMIC_NON_FACET_SUFFIXES)
                and (
                    not field.startswith("enr_context_")
                    or field in cls._SAFE_CONTEXT_FACET_FIELDS
                )
            )
        }

    def facets(self) -> dict:
        """Return distinct values and doc counts for all filterable fields.

        Streams bounded batches containing only metadata fields — no vectors or
        text. Deduplicates by doc_id across batches so counts reflect documents,
        not chunks.
        Tags are split on commas and counted individually.
        Dynamic fields (not in _FACET_KEY_MAP) are automatically included.
        """
        total_chunks = self.count_chunks()
        if total_chunks == 0:
            return {"total_docs": 0, "total_chunks": 0}
        def _op():
            available = self._metadata_subfields()

            # Discover dynamic fields, excluding context narratives/JSON that
            # would be corrupted by the comma-splitting facet logic.
            dynamic_fields = self._dynamic_facet_fields(available)

            projection = {"doc_id": "doc_id"}
            for field in self._FACET_KEY_MAP:
                if field in available:
                    projection[field] = f"metadata.{field}"
            for field in dynamic_fields:
                projection[field] = f"metadata.{field}"
            if "tags" in available:
                projection["tags"] = "metadata.tags"

            batches = (
                self._vs.table.search(None)
                .select(projection)
                .to_batches(batch_size=self._FACET_SCAN_BATCH_SIZE)
            )

            # Deduplicate by doc_id and count facet values across batches.
            seen: set[str] = set()
            all_counted_fields = set(self._FACET_KEY_MAP.keys()) | dynamic_fields
            counters: dict[str, Counter] = {f: Counter() for f in all_counted_fields}
            tag_counter: Counter = Counter()

            for batch in batches:
                row_count = batch.num_rows
                if row_count == 0:
                    continue
                names = set(batch.schema.names)
                doc_ids = batch.column(batch.schema.get_field_index("doc_id")).to_pylist()
                field_columns = {
                    field: (
                        batch.column(batch.schema.get_field_index(field)).to_pylist()
                        if field in names
                        else [None] * row_count
                    )
                    for field in all_counted_fields
                }
                tags_col = (
                    batch.column(batch.schema.get_field_index("tags")).to_pylist()
                    if "tags" in names
                    else [None] * row_count
                )

                for i, did in enumerate(doc_ids):
                    if not did or did in seen:
                        continue
                    seen.add(did)

                    for field in all_counted_fields:
                        value = field_columns[field][i]
                        if value and str(value).strip():
                            for item in str(value).split(","):
                                item = item.strip()
                                if item:
                                    counters[field][item] += 1

                    raw_tags = tags_col[i]
                    if raw_tags and str(raw_tags).strip():
                        for tag in str(raw_tags).split(","):
                            tag = tag.strip()
                            if tag:
                                tag_counter[tag] += 1

            if not seen:
                return {"total_docs": 0, "total_chunks": total_chunks}

            def _to_list(counter: Counter) -> list[dict]:
                return [{"value": v, "count": c} for v, c in counter.most_common()]

            result: dict = {
                "tags": _to_list(tag_counter),
                "total_docs": len(seen),
                "total_chunks": total_chunks,
            }
            for f, key in self._FACET_KEY_MAP.items():
                result[key] = _to_list(counters[f])
            # Dynamic fields use their own name as the result key
            for f in dynamic_fields:
                facet_list = _to_list(counters[f])
                if facet_list:  # only include if there are non-empty values
                    result[f] = facet_list

            return result

        return self._run_read_with_recovery(_op, {"total_docs": 0, "total_chunks": 0})

    def get_vector(self, chunk_uid: str) -> list[float] | None:
        """Retrieve the stored embedding vector for a chunk by its UID (doc_id::loc).

        Used by MMR diversity and cosine fallback reranking. Returns None if
        the chunk is not found or the table doesn't exist yet.
        """
        def _op():
            rows = (
                self._vs.table.search(None)
                .where(f"id = '{self._sql_escape(chunk_uid)}'", prefilter=True)
                .select(["vector"])
                .limit(1)
                .to_list()
            )
            if not rows:
                return None
            vec = rows[0].get("vector")
            if vec is None:
                return None
            # Convert from Arrow/numpy to plain list if needed
            if hasattr(vec, "tolist"):
                return vec.tolist()
            return list(vec)

        return self._run_read_with_recovery(_op, None)

    def get_vectors(self, chunk_uids: list[str]) -> dict[str, list[float]]:
        """Batch-load stored vectors for chunk UIDs missing from search hits."""
        if not chunk_uids:
            return {}
        try:
            table = self._vs.table
        except TableNotFoundError:
            return {}

        unique_uids = list(dict.fromkeys(uid for uid in chunk_uids if uid))
        if not unique_uids:
            return {}
        in_values = ", ".join(f"'{self._sql_escape(uid)}'" for uid in unique_uids)
        rows = (
            table.search(None)
            .where(f"id IN ({in_values})", prefilter=True)
            .select(["id", "vector"])
            .limit(len(unique_uids))
            .to_list()
        )

        vectors: dict[str, list[float]] = {}
        for row in rows:
            uid = row.get("id")
            vec = row.get("vector")
            if not uid or vec is None:
                continue
            vectors[str(uid)] = vec.tolist() if hasattr(vec, "tolist") else list(vec)
        return vectors

    def get_chunk(self, doc_id: str, loc: str) -> SearchHit | None:
        """Get a single chunk by doc_id and loc.

        Uses predicate pushdown with BTREE index — O(log n), no full scan.
        Loads text + metadata for the matching row only; no vectors.
        """
        def _op():
            esc_doc = self._sql_escape(doc_id)
            esc_loc = self._sql_escape(loc)
            rows = (
                self._vs.table.search(None)
                .where(f"doc_id = '{esc_doc}' AND metadata.loc = '{esc_loc}'", prefilter=True)
                .select(["doc_id", "text", "metadata"])
                .limit(1)
                .to_list()
            )
            if not rows:
                return None
            return self._row_to_hit(rows[0])

        return self._run_read_with_recovery(_op, None)

    def get_doc_chunks(self, doc_id: str) -> list[SearchHit]:
        """Get all chunks for a document, sorted by loc.

        Uses predicate pushdown with BTREE index — O(log n + k), no full scan.
        Loads text + metadata for matching rows only; no vectors.
        """
        def _op():
            esc_doc = self._sql_escape(doc_id)
            rows = (
                self._vs.table.search(None)
                .where(f"doc_id = '{esc_doc}'", prefilter=True)
                .select(["doc_id", "text", "metadata"])
                .to_list()
            )
            hits = [self._row_to_hit(row) for row in rows]
            hits.sort(key=lambda h: h.loc)
            return hits

        return self._run_read_with_recovery(_op, [])


def _looks_like_corrupt_lance_error(exc: Exception) -> bool:
    """Return True when a store-open failure matches known Lance corruption signatures."""
    message = str(exc).lower()
    return any(marker in message for marker in _CORRUPT_LANCE_MARKERS)


def recover_corrupt_table(
    index_root: str | Path,
    table_name: str,
    logger_obj: logging.Logger | None = None,
) -> LanceDBStore | None:
    """Walk Lance versions backward, rebuild from last readable snapshot, return fresh store."""
    import lance

    active_logger = logger_obj or logger
    lance_path = Path(index_root) / f"{table_name}.lance"
    if not lance_path.exists():
        return None

    active_logger.warning("Corruption detected — attempting auto-recovery for %s", lance_path)

    try:
        dataset = lance.dataset(str(lance_path))
        versions = sorted(dataset.versions(), key=lambda item: item["version"], reverse=True)
    except Exception as exc:
        active_logger.error("Cannot read dataset versions: %s", exc)
        return None

    clean_version = None
    for version_info in versions:
        version = version_info["version"]
        try:
            clean_dataset = lance.dataset(str(lance_path), version=version)
            clean_dataset.to_table(limit=1)
            clean_version = version
            break
        except Exception:
            continue

    if clean_version is None:
        active_logger.error("No readable version found — manual recovery needed")
        return None

    clean_table = lance.dataset(str(lance_path), version=clean_version).to_table()
    active_logger.info(
        "Found clean version %d with %d rows — rebuilding table",
        clean_version,
        clean_table.num_rows,
    )

    corrupt_path = Path(f"{lance_path}.corrupt")
    if corrupt_path.exists():
        shutil.rmtree(corrupt_path)
    shutil.move(str(lance_path), str(corrupt_path))
    lance.write_dataset(clean_table, str(lance_path))

    rebuilt = lance.dataset(str(lance_path))
    rebuilt.to_table(limit=1)
    active_logger.info(
        "Recovery complete: %d rows restored. Corrupt backup at %s",
        rebuilt.count_rows(),
        corrupt_path,
    )
    return LanceDBStore(index_root, table_name)


def open_store_with_recovery(
    index_root: str | Path,
    table_name: str = "chunks",
    *,
    logger_obj: logging.Logger | None = None,
    auto_recover: bool = True,
) -> LanceDBStore:
    """Open LanceDBStore and auto-recover from known corruption signatures when possible."""
    try:
        return LanceDBStore(index_root, table_name)
    except Exception as exc:
        if not auto_recover or not _looks_like_corrupt_lance_error(exc):
            raise
        recovered = recover_corrupt_table(index_root, table_name, logger_obj=logger_obj)
        if recovered is not None:
            return recovered
        raise
